# Worksheet 2

## Question 1

In [68]:
A = [[6, -2], [-2, 9]]

Step 1:

Av = Lambda(v)

Step 2: Rephrase the equation

(A - Lambda(I))v = 0

Step 3: Determinant of the A - Lambda(I) equals to 0

det(A - Lambda(I)) = 0

Step 4: Solve for Lambda

det([6 - lambda, -2], [-2, 9 - lambda]) = 0

Step 5: Solve for det

In [3]:
import numpy as np

lambda^2 - 15 lambda + 54 - 4 = 0

lamb = 5, 10

Eigenvalues = 5 and 10

### Eigenvalues = 10

In [45]:
lamb1 = 10

In [46]:
A = np.array([[6, -2], [-2, 9]])

In [47]:
I = np.array([[lamb1, 0], [0, lamb1]])

In [48]:
X1 = A - I

In [49]:
print(X1)

[[-4 -2]
 [-2 -1]]


y = -2x

Eigenvector = [1, -2] since if x = 1 then y = -2

### Eigenvalues = 5

In [50]:
lamb2 = 5
I = np.array([[lamb2, 0], [0, lamb2]])
X2 = A - I
print(X)

[[ 1 -2]
 [-2  4]]


x = 2y

Eigenvector = [2, 1] since if x = 2 then y = 1

### Check using the PDP-1 to see if it's diaganolized (the eigenvalues and eigenvectors are correct)

In [35]:
D = np.array([[lamb1, 0], [0, lamb2]])

In [51]:
e1 = np.array([[1],[-2]])

In [54]:
e2 = np.array([[2], [1]])

In [57]:
P = np.hstack((e1, e2))
print(P)

[[ 1  2]
 [-2  1]]


In [61]:
Pi = np.linalg.inv(P)

In [62]:
print(Pi)

[[ 0.2 -0.4]
 [ 0.4  0.2]]


In [65]:
result = P @ D @ Pi

In [66]:
print(result)

[[ 6. -2.]
 [-2.  9.]]


### Using Scipy to solve

In [67]:
import numpy as np
import scipy.linalg as la

In [70]:
print(la.eig(A)) # Eigenvalues are 5 and 10

(array([ 5.+0.j, 10.+0.j]), array([[-0.89442719,  0.4472136 ],
       [-0.4472136 , -0.89442719]]))


## Question 2

In [72]:
import pandas as pd

In [76]:
india = pd.read_csv('W2/ws2_india.csv')

In [77]:
print(india)

                       Region  Total  Assamese  Bengali  Bodo  Dogri  \
0             Jammu & Kashmir  10000         7       16     0   2004   
1            Himachal Pradesh  10000         2        9     0     34   
2                      Punjab  10000         1       10     0      7   
3                  Chandigarh  10000         4       59     0     10   
4                 Uttarakhand  10000         2      150     0      5   
5                     Haryana  10000         2       28     0      1   
6                NCT of Delhi  10000         5      129     0      4   
7                   Rajasthan  10000         0       12     0      1   
8               Uttar Pradesh  10000         1       12     0      0   
9                       Bihar  10000         0       78     0      0   
10                     Sikkim  10000        14      114     1      4   
11          Arunachal Pradesh  10000       390      727    51      7   
12                   Nagaland  10000        87      378    37   

In [79]:
india_c = india.drop(['Region', 'Total', 'Total_Scheduled', 'Non_Scheduled'], axis = 1)

In [89]:
india_c.head()

,Assamese,Bengali,Bodo,Dogri,Gujarati,Hindi,Kannada,Kashmiri,Konkani,Maithili,...,Marathi,Nepali,Odia,Punjabi,Sanskrit,Santali,Sindhi,Tamil,Telugu,Urdu
0,7,16,0,2004,15,2083,6,5327,0,9,...,18,8,175,0,0,0,12,11,16,9727
1,2,9,0,34,15,8588,1,83,0,2,...,130,5,896,1,1,0,2,2,8,9791
2,1,10,0,7,5,935,1,1,0,4,...,8,4,8982,0,0,0,4,3,10,9986
3,4,59,0,10,15,7360,4,13,1,19,...,62,18,2203,0,0,1,53,13,100,9981
4,2,150,0,5,4,8915,1,2,0,3,...,105,4,261,0,0,3,3,3,422,9944


In [91]:
india_m = india_c.to_numpy()

### Manual Covariance Calculation

In [93]:
# Compute Mean of Each Column
sum_col = np.sum(india_m, axis = 0)

In [97]:
sum_row = np.sum(india_m, axis = 1)

In [98]:
print(sum_row)

[19454 19575 19968 19932 19833 19954 19889 18925 19994 18694 14717  5553
  2365 11640  2470 13955  2926 18555 19892 17985 18460 18130 18527 19647
 19091 13272 18556 19913 19986 19988 18517]
